include("lib/sim.jl")
include("lib/viz.jl")
include("lib/data.jl")

function main()
    # Specify the base filename for the results you want to plot,
    # which can be generated by running the `run_sim.jl` script with your desired hyperparameters.
    base_filename = "d3_p2_m2_k15_n200000_M1000"

    println("1. Loading results for `$base_filename`...")
    local params, mdi_df
    try
        params, mdi_df = load_results(base_filename)
    catch e
        if isa(e, ErrorException) && contains(e.msg, "Result files not found")
            println("\nError: Could not find results for `$base_filename`.")
            println("Make sure the files exist and that the filename is correctely spelled.")
            return
        else
            rethrow()
        end
    end
    println("   ...done.")

    println("2. Processing results...")
    results_noisy, results_signal = process_results(mdi_df, params)
    println("   ...done.")

    println("3. Generating plot...")
    fig = plot_mdi(
        params;
        results_noisy=results_noisy,
        results_signal=results_signal
    )
    println("   ...done.")

    display(fig)

    # Save the plot to a file
    # save_path = "results/$(base_filename)_plot.pdf"
    # savefig(fig, save_path)
    # println("Plot saved to `$save_path`")
end

main()